FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.22@sha256:450e3822c7a135e1463cd83e51c8e2eb03b86a02113c89424e6f0f8344bb4168 as build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM docker.io/python:3.12-alpine@sha256:ef097620baf1272e38264207003b0982285da3236a20ed829bf6bbf1e85fe3cb

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="wp-ansible"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/wp-ansible"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/wp-ansible"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/wp-ansible"

ARG TARGETOS
ARG TARGETARCH
ARG ANSIBLE_VERSION

# renovate: datasource=pypi depName=ansible
ENV ANSIBLE_VERSION="${ANSIBLE_VERSION:-9.5.1}"

RUN apk --update add --virtual .build-deps python3-dev libffi-dev build-base && \
    apk add --no-cache bash git curl rsync openssh-client sshpass && \
    apk upgrade --no-cache libcrypto3 libssl3 && \
    pip install -qq --no-cache-dir --upgrade pip && \
    pip install -qq --no-cache-dir ansible=="${ANSIBLE_VERSION}" \
      boto3 hcloud pywinrm passlib jsonschema && \
    apk del .build-deps && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/* && \
    rm -rf /root/.cache/

COPY --from=build /src/dist/wp-ansible /bin/wp-ansible
ENTRYPOINT ["/bin/wp-ansible"]
