FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.25.2@sha256:1c91b4f4391774a73d6489576878ad3ff3161ebc8c78466ec26e83474855bfcf AS build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM docker.io/python:3.14-alpine@sha256:8373231e1e906ddfb457748bfc032c4c06ada8c759b7b62d9c73ec2a3c56e710

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="wp-ansible"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/wp-ansible"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/wp-ansible"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/wp-ansible"

ARG TARGETOS
ARG TARGETARCH
ARG ANSIBLE_VERSION

# renovate: datasource=pypi depName=ansible
ENV ANSIBLE_VERSION="${ANSIBLE_VERSION:-12.1.0}"

RUN apk --update add --virtual .build-deps python3-dev libffi-dev build-base && \
    apk add --no-cache bash git curl rsync openssh-client sshpass && \
    apk upgrade --no-cache libcrypto3 libssl3 xz-libs sqlite-libs && \
    pip install -qq --no-cache-dir --upgrade pip && \
    pip install -qq --no-cache-dir ansible=="${ANSIBLE_VERSION}" \
      boto3 hcloud pywinrm passlib jsonschema && \
    apk del .build-deps && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/* && \
    rm -rf /root/.cache/

COPY --from=build /src/dist/wp-ansible /bin/wp-ansible
ENTRYPOINT ["/bin/wp-ansible"]
